# Generated by Django 4.0.6 on 2022-07-24 10:22

from django.db import migrations, models
import video.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=250)),
                ('video', models.FileField(upload_to='video/%y', validators=[video.validators.file_size, video.validators.validate_file_extension, video.validators.file_length])),
                ('dateofupload', models.DateField(null=True)),
            ],
        ),
    ]
