# Generated by Django 4.0.6 on 2022-07-24 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='totalprice',
        ),
    ]
