# Generated by Django 4.0.6 on 2022-07-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_remove_video_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='totalprice',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
