# Generated by Django 4.0.6 on 2022-07-24 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_totalprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='totalprice',
        ),
    ]
